# Generated by Django 6.0.5 on 2026-05-20 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(help_text='Ej: Se finalizó el diagnóstico de la placa y se procedió a reemplazar los capacitores.')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avances/')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='inventario.ordenservicio')),
            ],
            options={
                'verbose_name': 'Avance de Orden',
                'verbose_name_plural': 'Avances de Órdenes',
                'ordering': ['-fecha'],
            },
        ),
    ]
