# Generated by Django 6.0.5 on 2026-05-25 19:08

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_avanceorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='codigo_rastreo',
            field=models.CharField(default=inventario.models.generar_codigo_unico, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='equipo',
            field=models.CharField(help_text='Ej. RTX 3060 EVGA XC GAMING, Laptop HP Pavilion 15, etc.', max_length=200),
        ),
    ]
