# Generated by Django 6.0.5 on 2026-05-25 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_ordenservicio_codigo_rastreo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='estado',
            field=models.CharField(choices=[('ESPERANDO', 'Esperando Ingreso'), ('RECIBIDO', 'Recibido'), ('DIAGNOSTICO', 'En Diagnóstico'), ('REPUESTOS', 'Esperando Repuestos'), ('REPARADO', 'Reparado / Listo para entrega'), ('ENTREGADO', 'Entregado al cliente'), ('CANCELADO', 'No reparable / Cancelado')], default='ESPERANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria'),
        ),
    ]
