# Generated by Django 6.0.6 on 2026-07-05 01:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_ordenservicio_presupuesto_estado_lineapresupuesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='costo_estimado',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='diagnostico_tecnico',
        ),
        migrations.AlterField(
            model_name='avanceorden',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='cliente_nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='cliente_telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='estado',
            field=models.CharField(choices=[('ESPERANDO', 'Esperando Ingreso'), ('RECIBIDO', 'Recibido'), ('DIAGNOSTICO', 'En Diagnóstico'), ('REPUESTOS', 'Reparando / Esperando Repuestos'), ('REPARADO', 'Reparado / Listo para entrega'), ('ENTREGADO', 'Entregado al cliente'), ('CANCELADO', 'No reparable / Cancelado')], db_index=True, default='ESPERANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='fecha_ingreso',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='presupuesto_estado',
            field=models.CharField(choices=[('SIN_PRESUPUESTO', 'Sin Presupuesto'), ('PENDIENTE', 'Pendiente por Aprobar'), ('APROBADO', 'Aprobado por el Cliente'), ('RECHAZADO', 'Rechazado por el Cliente')], db_index=True, default='SIN_PRESUPUESTO', max_length=20, verbose_name='Estado del Presupuesto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
