# Generated by Django 6.0.6 on 2026-07-05 02:33

import django.db.models.deletion
import inventario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_producto_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='PedidoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('codigo_seguimiento', models.CharField(default=inventario.models.generar_codigo_unico, editable=False, max_length=20, unique=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido de Catálogo',
                'verbose_name_plural': 'Pedidos de Catálogo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PedidoImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('COTIZANDO', 'Cotizando'), ('CONFIRMADO', 'Confirmado'), ('COMPRADO', 'Comprado en Tienda'), ('EN_TRANSITO', 'En Tránsito'), ('EN_ADUANA', 'En Aduana'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='COTIZANDO', max_length=20)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ves', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('productos_json', models.TextField(blank=True, verbose_name='Productos (JSON)')),
                ('codigo_seguimiento', models.CharField(default=inventario.models.generar_codigo_unico, editable=False, max_length=20, unique=True)),
                ('nota', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido de Importación',
                'verbose_name_plural': 'Pedidos de Importación',
                'ordering': ['-fecha'],
            },
        ),
    ]
