# Generated by Django 6.0.6 on 2026-07-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_pedidoimportacion_pago_inicial_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoimportacion',
            name='saldo_pendiente_ves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo pendiente (Bs al entregar)'),
        ),
        migrations.AddField(
            model_name='pedidoimportacion',
            name='tasa_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tasa Bs/$ al entregar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre completo'),
        ),
    ]
