# Generated by Django 6.0.5 on 2026-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_ordenservicio_estado_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/'),
        ),
        migrations.AlterField(
            model_name='avanceorden',
            name='descripcion',
            field=models.TextField(help_text='Ej: Se finalizó el diagnóstico...'),
        ),
    ]
