# Generated by Django 6.0.5 on 2026-05-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_ordenservicio_qr_code_alter_avanceorden_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='presupuesto_estado',
            field=models.CharField(choices=[('SIN_PRESUPUESTO', 'Sin Presupuesto'), ('PENDIENTE', 'Pendiente por Aprobar'), ('APROBADO', 'Aprobado por el Cliente'), ('RECHAZADO', 'Rechazado por el Cliente')], default='SIN_PRESUPUESTO', max_length=20, verbose_name='Estado del Presupuesto'),
        ),
        migrations.CreateModel(
            name='LineaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255, verbose_name='Repuesto o Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto ($)')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_presupuesto', to='inventario.ordenservicio')),
            ],
            options={
                'verbose_name': 'Línea de Presupuesto',
                'verbose_name_plural': 'Líneas de Presupuesto',
            },
        ),
    ]
