# Generated by Django 6.0.6 on 2026-07-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
