# Generated by Django 6.0.6 on 2026-07-05 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_ordenservicio_usuario_pedidocatalogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocatalogo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidocatalogo',
            name='precio_unitario_usd',
        ),
        migrations.RemoveField(
            model_name='pedidocatalogo',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedidocatalogo',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='pedidocatalogo',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='pedidocatalogo',
            name='productos_json',
            field=models.TextField(blank=True, verbose_name='Productos (JSON)'),
        ),
        migrations.AddField(
            model_name='pedidoimportacion',
            name='carrier_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Carrier / Courier'),
        ),
        migrations.AddField(
            model_name='pedidoimportacion',
            name='carrier_tracking',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° de Seguimiento'),
        ),
        migrations.AddField(
            model_name='pedidoimportacion',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='pedidoimportacion',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='pedidocatalogo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidocatalogo',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidocatalogo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pedidoimportacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_TRANSITO_EXTERIOR', 'En Tránsito Exterior'), ('EN_TRANSITO_VENEZUELA', 'En Tránsito a Venezuela'), ('LISTO_RETIRAR', 'Listo para Retirar'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='pedidoimportacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
