# Generated by Django 6.0.6 on 2026-07-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_remove_pedidocatalogo_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoimportacion',
            name='pago_inicial_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Pago inicial (USD)'),
        ),
        migrations.AddField(
            model_name='pedidoimportacion',
            name='pago_inicial_ves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Pago inicial (Bs)'),
        ),
        migrations.AddField(
            model_name='pedidoimportacion',
            name='saldo_pendiente_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo pendiente (USD)'),
        ),
        migrations.AddField(
            model_name='pedidoimportacion',
            name='tasa_confirmacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tasa Bs/$ al confirmar'),
        ),
    ]
