# Generated by Django 6.0.6 on 2026-07-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_pedidoimportacion_saldo_pendiente_ves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocatalogo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado / Rechazado'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20),
        ),
    ]
