# Generated by Django 6.0.6 on 2026-07-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_pedidocatalogo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (USD)')),
                ('monto_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto (Bs)')),
                ('metodo', models.CharField(choices=[('PAGO_MOVIL', 'Transferencia / Pago Móvil'), ('BINANCE', 'Binance Pay'), ('WALLY', 'Wally'), ('EFECTIVO', 'Divisas Efectivo')], max_length=20, verbose_name='Método de Pago')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha del Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('concepto', models.CharField(max_length=150, verbose_name='Concepto')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Verificación'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('orden_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventario.ordenservicio', verbose_name='Orden de Servicio')),
                ('pedido_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventario.pedidocatalogo', verbose_name='Pedido de Catálogo')),
                ('pedido_importacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventario.pedidoimportacion', verbose_name='Pedido de Importación')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
