# Generated by Django 6.0.6 on 2026-07-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Verificación'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('PAGO_MOVIL', 'Transferencia / Pago Móvil'), ('BINANCE', 'Binance Pay'), ('WALLY', 'Wally'), ('EFECTIVO', 'Divisas Efectivo')], db_index=True, max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pedidocatalogo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado / Rechazado'), ('CERRADA', 'Cerrada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoimportacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_TRANSITO_EXTERIOR', 'En Tránsito Exterior'), ('EN_TRANSITO_VENEZUELA', 'En Tránsito a Venezuela'), ('LISTO_RETIRAR', 'Listo para Retirar'), ('ENTREGADO', 'Entregado')], db_index=True, default='PENDIENTE', max_length=25),
        ),
    ]
